type: train

# Data
train_samples: "./flist/DAVIS-VI_tra_OPN_30.npy"
val_samples: "./flist/DAVIS-VI_val_OPN_20.npy"
test_samples: "./flist/DAVIS-VI_val_OPN_20.npy"
input_size: 512
gt_ratio: 1
num_frames: 1
val_num_frames: 8
dataset_repeat: 1
batch_size: 2
num_workers: 4

# Model
hrnet_path: "../ZZZ_model/models/hrnet.py"
hrnet_extra_name: "w32_extra"
freeze_backbone: false
decoder_channels: 32
checkpoint: "runs/simple_hrnet/best_iou.pt"

# Train
n_epochs: 1000
learning_rate: 1.0e-4
weight_decay: 0.0
seed: 666666
amp: true
validate_every: 10
threshold: 0.5

# Output
save_dir: "runs/simple_hrnet"
visualization_dir: "runs/simple_hrnet/vis"
